//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertretungsplan_Uploader.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vertretungsplan_Uploader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lösche temporäre Dateien... ähnelt.
        /// </summary>
        internal static string DELETE_TEMPORARY_FILES {
            get {
                return ResourceManager.GetString("DELETE_TEMPORARY_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei schuelerplan.html wurde lokal gelöscht. Lösche online... ähnelt.
        /// </summary>
        internal static string DELETED_LOCAL_FILE {
            get {
                return ResourceManager.GetString("DELETED_LOCAL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde eine Änderung im Pfad {0} erkannt, letzte Änderung: {1} ähnelt.
        /// </summary>
        internal static string DETECTED_CHANGE {
            get {
                return ResourceManager.GetString("DETECTED_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler beim Ändern der letzten Bearbeitungszeit aufgetreten: ähnelt.
        /// </summary>
        internal static string ERROR_CHANGING_LAST_EDIT_TIME {
            get {
                return ResourceManager.GetString("ERROR_CHANGING_LAST_EDIT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vor einem manuellen Sync müssen alle Einstellungen korrekt eingestellt sein! ähnelt.
        /// </summary>
        internal static string ERROR_MANUAL_SYNC_MISSING_SETTINGS {
            get {
                return ResourceManager.GetString("ERROR_MANUAL_SYNC_MISSING_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler beim Lesen der Quelldatei aufgetreten: {0} ähnelt.
        /// </summary>
        internal static string ERROR_READING_SOURCE_FILE {
            get {
                return ResourceManager.GetString("ERROR_READING_SOURCE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es fehlen einige Einstellungen. Die Einstellungen konnten nicht gespeichert werden! ähnelt.
        /// </summary>
        internal static string ERROR_SAVE_SETTINGS_MISSING_SETTINGS {
            get {
                return ResourceManager.GetString("ERROR_SAVE_SETTINGS_MISSING_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein unbekannter Fehler aufgetreten: {0} ähnelt.
        /// </summary>
        internal static string ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler beim Hochladen der Datei aufgetreten: {0} ähnelt.
        /// </summary>
        internal static string ERROR_UPLOADING_FILE {
            get {
                return ResourceManager.GetString("ERROR_UPLOADING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JSON-Datei erstellt, beginne mit dem Upload... ähnelt.
        /// </summary>
        internal static string GENERATED_JSON_FILE {
            get {
                return ResourceManager.GetString("GENERATED_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine vorherigen Einstellungen gefunden, bitte konfigurieren! ähnelt.
        /// </summary>
        internal static string LOAD_SETTINGS_NO_SETTINGS_CONFIGURED {
            get {
                return ResourceManager.GetString("LOAD_SETTINGS_NO_SETTINGS_CONFIGURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei enthält keine Merkmale, stoppe Bearbeitung! ähnelt.
        /// </summary>
        internal static string NO_CHARACTERISTICS_FOUND {
            get {
                return ResourceManager.GetString("NO_CHARACTERISTICS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigung abgeschlossen ({0}) ähnelt.
        /// </summary>
        internal static string NOTIFICATION_COMPLETE {
            get {
                return ResourceManager.GetString("NOTIFICATION_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein neuer Vertretungsplan ist jetzt online ähnelt.
        /// </summary>
        internal static string NOTIFICATION_NEW_VP_ONLINE {
            get {
                return ResourceManager.GetString("NOTIFICATION_NEW_VP_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vertretungsplan ähnelt.
        /// </summary>
        internal static string NOTIFY_ICON_TEXT {
            get {
                return ResourceManager.GetString("NOTIFY_ICON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon notifyIcon {
            get {
                object obj = ResourceManager.GetObject("notifyIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtige mobile Endgeräte via Gcm... ähnelt.
        /// </summary>
        internal static string NOTIFYING_MOBILE_DEVICES {
            get {
                return ResourceManager.GetString("NOTIFYING_MOBILE_DEVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen gespeichert! ähnelt.
        /// </summary>
        internal static string SAVED_SETTINGS {
            get {
                return ResourceManager.GetString("SAVED_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen an den Uploadmanager übergeben. ähnelt.
        /// </summary>
        internal static string SETTINGS_DELIVERED_TO_MANAGER {
            get {
                return ResourceManager.GetString("SETTINGS_DELIVERED_TO_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen erfolgreich aus settings.bin geladen ähnelt.
        /// </summary>
        internal static string SUCCESSFULLY_LOADED_SETTINGS {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_LOADED_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei erfolgreich in {0}.html umbenannt, generiere JSON-Datei... ähnelt.
        /// </summary>
        internal static string SUCCESSFULLY_RENAMED_FILE {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_RENAMED_FILE", resourceCulture);
            }
        }
    }
}
